### ISSUE TITLE
The top section appears when resizing the browser window

### ISSUE THREAD

**Issue by philcable** [washingtonstateuniversity/WSU-25x2030-Theme#26]
We don't want that to happen. Not sure if this happens on device orientation change, but if so, that should be fixed too.

**Comment by jeremyfelt** [comment]
It looks like this is built into doormat directly as intentional behavior - https://github.com/jh3y/doormat/blob/8bc1b2b2f251086e34578e3fa264fd48d6dec064/src/js/doormat.js#L58-L62

We probably need to launch with this and then determine if it's really necessary to fix.

**Comment by philcable** [comment]
Since we aren't using doormat anymore, I'll go ahead and close this :)
