### ISSUE TITLE
Expect url rewrite by category on evidence page/section to be sharable and useable.

### ISSUE THREAD

**Issue by slocker3** [washingtonstateuniversity/WSU-25x2030-Theme#70]
I would expect to be able to link to a category, e.g., https://wsu.edu/drive-to-25/the-evidence/category/health-sciences/, off of the Evidence page.

**Comment by philcable** [comment]
Sorry about that - rewrites needed to be flushed. Should be set now!

**Comment by slocker3** [comment]
@philcable 👍 👍  thank you!!!
